/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.guessinggame;

import id.co.indocyber.guessinggame.model.WordModel;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class GuessingGame extends javax.swing.JFrame {

    WordModel modelWord;
    //String[] bankSoal = {"Pondok Indah","Sudirman","Tugu Tani","Citos","Gandaria City"};
//    WordModel soal1 = new WordModel("Pondok Indah", "Daerah Jakarta Selatan");
//    WordModel soal2 = new WordModel("Sudirman","Jalan Utama di Jakarta");
//    WordModel soal3 = new WordModel("Tugu Tani","Patung deket Monas");
//    WordModel soal4 = new WordModel("Citos","Mall di selatan Jakarta");
//    WordModel soal5 = new WordModel("Gandaria City","Mall anak muda");
//    WordModel[] bankSoal = {soal1,soal2,soal3,soal4,soal5};
      List<WordModel> bankSoal;
    /**
     * Creates new form GuessingGame
     */
    public GuessingGame() throws IOException {
        bankSoal = WordQuestionGenerator.createQuestionFromFile("C:/JAVA_LATIHAN/question.txt");
        //bankSoal = WordQuestionGenerator.createQuestionInCollection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soalTextField = new javax.swing.JTextField();
        jawabanTextField = new javax.swing.JTextField();
        cekButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        commentLabel = new javax.swing.JLabel();
        mulaiButton = new javax.swing.JButton();
        HintButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        HintLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        soalTextField.setEditable(false);

        cekButton.setText("Periksa");
        cekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Jawaban:");

        commentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        commentLabel.setText("Belum ada jawaban");

        mulaiButton.setText("Mulai");
        mulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiButtonActionPerformed(evt);
            }
        });

        HintButton.setText("Bantuan dong");
        HintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HintButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Hint: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mulaiButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HintButton)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cekButton)
                    .addComponent(jawabanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(commentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HintLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mulaiButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(HintButton)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jawabanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(cekButton)
                .addGap(30, 30, 30)
                .addComponent(commentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiButtonActionPerformed
        // TODO add your handling code here:
        int soalIndex = (int) Math.floor(Math.random() * bankSoal.size());//floor digunakan untuk megubah nilai menjadi positif
        
        modelWord = bankSoal.get(soalIndex);//bankSoal[soalIndex];
        soalTextField.setText(modelWord.acakHuruf());
        
//        basicword = basicword.toUpperCase();//touppercase untuk mengubah huruf menjadi huruf kapital
//        String [] arrayOfWord = basicWord.split("");
//        
//        for (int i = 0; i < arrayOfWord.length; i++) {
//            System.out.println(arrayOfWord[i]);
//            
//        }
//       
//        Arrays.sort(arrayOfWord);//sort sebagai penyortir huruf ascending
//        System.out.println("\nSeltelan di sort\n");
//        StringBuilder sb = new StringBuilder();
//        for (int i = 0; i < arrayOfWord.length; i++) {
//            //System.out.println(arrayOfWord[i]);
//            sb.append(arrayOfWord[i]);//append untuk menampung array
//        }
//        
//        String soal = sb.toString();//mengubah array menjadi string
//        System.out.println("Soal yang harus di jawab: " + soal.trim());//trim untuk menghilangkan spasi depan dan belakang
//        soalTextField.setText(soal.trim());
    }//GEN-LAST:event_mulaiButtonActionPerformed

    private void cekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekButtonActionPerformed
        // TODO add your handling code here:
        
        String jawaban = jawabanTextField.getText().trim();
        modelWord.setJawaban(jawaban);
        if (modelWord.cekJawaban()) {
            commentLabel.setText("Jenius!");
            
        }else {
            commentLabel.setText("Coba lagi");
        }
    }//GEN-LAST:event_cekButtonActionPerformed

    private void HintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HintButtonActionPerformed
        // TODO add your handling code here:
        HintLabel.setText(modelWord.getHint());
    }//GEN-LAST:event_HintButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new GuessingGame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GuessingGame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HintButton;
    private javax.swing.JLabel HintLabel;
    private javax.swing.JButton cekButton;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jawabanTextField;
    private javax.swing.JButton mulaiButton;
    private javax.swing.JTextField soalTextField;
    // End of variables declaration//GEN-END:variables
}
